Repository Team-MAUV/humanityWebApp, pull requests merged in 2020-11, with the labels that each got.

#51 Add new beneficiary create operation
  controllers/Volunteer.php
  controllers/register.php
  models/register_model.php
  models/volunteer_model.php
  public/beneficiery_case/Enola Holmes (2020) [720p] [WEBRip] [YTS.MX].torrent
  views/register/buyRegForm.php
  views/register/donRegForm.php
  views/register/volRegForm.php
  views/volunteer/dashboard/addNewBeneficiary.php
Labels: Manuli

#50 UI changed Buyer
  controllers/Buyer.php
  controllers/Donor.php
  public/css/buy-cart-view.css
  public/css/buy-layout_style.css
  public/css/buy-market-index.css
  public/css/buy-market-profile.css
  public/css/buy-pages.css
  public/css/buy-product-category.css
  public/css/buy-product-view.css
  public/images/avatar.png
  public/images/ewaste.jpeg
  public/images/p-glass.jpg
  public/images/p-paper.jpg
  public/images/p-plastic.jpg
  views/buyer/buyer-home.php
  views/buyer/buyer-index.php
  views/buyer/contact_us.php
  views/buyer/market-buyer-home.php
  views/buyer/market-buyer-index.php
  views/buyer/market-buyer-profile.php
  views/buyer/market-cart.php
  views/buyer/market-product-category.php
  views/buyer/market-product-view.php
  views/buyer/product-page.php
Labels: Uthpala

#54 Database
  db dump file/humanity - nov 12.sql
Labels: Manuli

#53 staff ui issues almost corrected
  views/session_incharge/dashboard/media_gallary.php
  views/staff/dashboard/staff_gallery.php
Labels: Vigani
